; Auto-generated. Do not edit!


(cl:in-package test_pkg-msg)


;//! \htmlinclude TimerResult.msg.html

(cl:defclass <TimerResult> (roslisp-msg-protocol:ros-message)
  ((total_time_elapsed
    :reader total_time_elapsed
    :initarg :total_time_elapsed
    :type cl:float
    :initform 0.0))
)

(cl:defclass TimerResult (<TimerResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TimerResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TimerResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name test_pkg-msg:<TimerResult> is deprecated: use test_pkg-msg:TimerResult instead.")))

(cl:ensure-generic-function 'total_time_elapsed-val :lambda-list '(m))
(cl:defmethod total_time_elapsed-val ((m <TimerResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_pkg-msg:total_time_elapsed-val is deprecated.  Use test_pkg-msg:total_time_elapsed instead.")
  (total_time_elapsed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TimerResult>) ostream)
  "Serializes a message object of type '<TimerResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'total_time_elapsed))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TimerResult>) istream)
  "Deserializes a message object of type '<TimerResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'total_time_elapsed) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TimerResult>)))
  "Returns string type for a message object of type '<TimerResult>"
  "test_pkg/TimerResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TimerResult)))
  "Returns string type for a message object of type 'TimerResult"
  "test_pkg/TimerResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TimerResult>)))
  "Returns md5sum for a message object of type '<TimerResult>"
  "a626cb8f0c7f276ce9ff106ac8fb36d3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TimerResult)))
  "Returns md5sum for a message object of type 'TimerResult"
  "a626cb8f0c7f276ce9ff106ac8fb36d3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TimerResult>)))
  "Returns full string definition for message of type '<TimerResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 total_time_elapsed # result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TimerResult)))
  "Returns full string definition for message of type 'TimerResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 total_time_elapsed # result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TimerResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TimerResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TimerResult
    (cl:cons ':total_time_elapsed (total_time_elapsed msg))
))
