; Auto-generated. Do not edit!


(cl:in-package test_pkg-msg)


;//! \htmlinclude TimerFeedback.msg.html

(cl:defclass <TimerFeedback> (roslisp-msg-protocol:ros-message)
  ((partial_time_elapsed
    :reader partial_time_elapsed
    :initarg :partial_time_elapsed
    :type cl:float
    :initform 0.0))
)

(cl:defclass TimerFeedback (<TimerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TimerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TimerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name test_pkg-msg:<TimerFeedback> is deprecated: use test_pkg-msg:TimerFeedback instead.")))

(cl:ensure-generic-function 'partial_time_elapsed-val :lambda-list '(m))
(cl:defmethod partial_time_elapsed-val ((m <TimerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_pkg-msg:partial_time_elapsed-val is deprecated.  Use test_pkg-msg:partial_time_elapsed instead.")
  (partial_time_elapsed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TimerFeedback>) ostream)
  "Serializes a message object of type '<TimerFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'partial_time_elapsed))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TimerFeedback>) istream)
  "Deserializes a message object of type '<TimerFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'partial_time_elapsed) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TimerFeedback>)))
  "Returns string type for a message object of type '<TimerFeedback>"
  "test_pkg/TimerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TimerFeedback)))
  "Returns string type for a message object of type 'TimerFeedback"
  "test_pkg/TimerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TimerFeedback>)))
  "Returns md5sum for a message object of type '<TimerFeedback>"
  "cc2a6c0f2999c8066afc8654096742d2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TimerFeedback)))
  "Returns md5sum for a message object of type 'TimerFeedback"
  "cc2a6c0f2999c8066afc8654096742d2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TimerFeedback>)))
  "Returns full string definition for message of type '<TimerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 partial_time_elapsed # feedback ~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TimerFeedback)))
  "Returns full string definition for message of type 'TimerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 partial_time_elapsed # feedback ~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TimerFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TimerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TimerFeedback
    (cl:cons ':partial_time_elapsed (partial_time_elapsed msg))
))
