// Auto-generated. Do not edit!

// (in-package test_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class TimerFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.partial_time_elapsed = null;
    }
    else {
      if (initObj.hasOwnProperty('partial_time_elapsed')) {
        this.partial_time_elapsed = initObj.partial_time_elapsed
      }
      else {
        this.partial_time_elapsed = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TimerFeedback
    // Serialize message field [partial_time_elapsed]
    bufferOffset = _serializer.float32(obj.partial_time_elapsed, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TimerFeedback
    let len;
    let data = new TimerFeedback(null);
    // Deserialize message field [partial_time_elapsed]
    data.partial_time_elapsed = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'test_pkg/TimerFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'cc2a6c0f2999c8066afc8654096742d2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    float32 partial_time_elapsed # feedback 
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TimerFeedback(null);
    if (msg.partial_time_elapsed !== undefined) {
      resolved.partial_time_elapsed = msg.partial_time_elapsed;
    }
    else {
      resolved.partial_time_elapsed = 0.0
    }

    return resolved;
    }
};

module.exports = TimerFeedback;
