// Generated by gencpp from file test_pkg/customMessage.msg
// DO NOT EDIT!


#ifndef TEST_PKG_MESSAGE_CUSTOMMESSAGE_H
#define TEST_PKG_MESSAGE_CUSTOMMESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_pkg
{
template <class ContainerAllocator>
struct customMessage_
{
  typedef customMessage_<ContainerAllocator> Type;

  customMessage_()
    : name()
    , value(0.0)  {
    }
  customMessage_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef float _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::test_pkg::customMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_pkg::customMessage_<ContainerAllocator> const> ConstPtr;

}; // struct customMessage_

typedef ::test_pkg::customMessage_<std::allocator<void> > customMessage;

typedef boost::shared_ptr< ::test_pkg::customMessage > customMessagePtr;
typedef boost::shared_ptr< ::test_pkg::customMessage const> customMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_pkg::customMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_pkg::customMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_pkg::customMessage_<ContainerAllocator1> & lhs, const ::test_pkg::customMessage_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_pkg::customMessage_<ContainerAllocator1> & lhs, const ::test_pkg::customMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test_pkg::customMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_pkg::customMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::customMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::customMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::customMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::customMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_pkg::customMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db3486341a840969e8845548decf6f11";
  }

  static const char* value(const ::test_pkg::customMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb3486341a840969ULL;
  static const uint64_t static_value2 = 0xe8845548decf6f11ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_pkg::customMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_pkg/customMessage";
  }

  static const char* value(const ::test_pkg::customMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_pkg::customMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# CustomMessage.msg\n"
"string name\n"
"float32 value\n"
;
  }

  static const char* value(const ::test_pkg::customMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_pkg::customMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct customMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_pkg::customMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_pkg::customMessage_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_PKG_MESSAGE_CUSTOMMESSAGE_H
