// Generated by gencpp from file test_pkg/TimerGoal.msg
// DO NOT EDIT!


#ifndef TEST_PKG_MESSAGE_TIMERGOAL_H
#define TEST_PKG_MESSAGE_TIMERGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_pkg
{
template <class ContainerAllocator>
struct TimerGoal_
{
  typedef TimerGoal_<ContainerAllocator> Type;

  TimerGoal_()
    : duration_time(0.0)  {
    }
  TimerGoal_(const ContainerAllocator& _alloc)
    : duration_time(0.0)  {
  (void)_alloc;
    }



   typedef float _duration_time_type;
  _duration_time_type duration_time;





  typedef boost::shared_ptr< ::test_pkg::TimerGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_pkg::TimerGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TimerGoal_

typedef ::test_pkg::TimerGoal_<std::allocator<void> > TimerGoal;

typedef boost::shared_ptr< ::test_pkg::TimerGoal > TimerGoalPtr;
typedef boost::shared_ptr< ::test_pkg::TimerGoal const> TimerGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_pkg::TimerGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_pkg::TimerGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_pkg::TimerGoal_<ContainerAllocator1> & lhs, const ::test_pkg::TimerGoal_<ContainerAllocator2> & rhs)
{
  return lhs.duration_time == rhs.duration_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_pkg::TimerGoal_<ContainerAllocator1> & lhs, const ::test_pkg::TimerGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test_pkg::TimerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_pkg::TimerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::TimerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::TimerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::TimerGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::TimerGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_pkg::TimerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "790a1b2f6126e5c09420d2652f44280f";
  }

  static const char* value(const ::test_pkg::TimerGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x790a1b2f6126e5c0ULL;
  static const uint64_t static_value2 = 0x9420d2652f44280fULL;
};

template<class ContainerAllocator>
struct DataType< ::test_pkg::TimerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_pkg/TimerGoal";
  }

  static const char* value(const ::test_pkg::TimerGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_pkg::TimerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Timer.action\n"
"float32 duration_time # goal\n"
;
  }

  static const char* value(const ::test_pkg::TimerGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_pkg::TimerGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.duration_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimerGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_pkg::TimerGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_pkg::TimerGoal_<ContainerAllocator>& v)
  {
    s << indent << "duration_time: ";
    Printer<float>::stream(s, indent + "  ", v.duration_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_PKG_MESSAGE_TIMERGOAL_H
