// Generated by gencpp from file test_pkg/TimerFeedback.msg
// DO NOT EDIT!


#ifndef TEST_PKG_MESSAGE_TIMERFEEDBACK_H
#define TEST_PKG_MESSAGE_TIMERFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_pkg
{
template <class ContainerAllocator>
struct TimerFeedback_
{
  typedef TimerFeedback_<ContainerAllocator> Type;

  TimerFeedback_()
    : partial_time_elapsed(0.0)  {
    }
  TimerFeedback_(const ContainerAllocator& _alloc)
    : partial_time_elapsed(0.0)  {
  (void)_alloc;
    }



   typedef float _partial_time_elapsed_type;
  _partial_time_elapsed_type partial_time_elapsed;





  typedef boost::shared_ptr< ::test_pkg::TimerFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_pkg::TimerFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct TimerFeedback_

typedef ::test_pkg::TimerFeedback_<std::allocator<void> > TimerFeedback;

typedef boost::shared_ptr< ::test_pkg::TimerFeedback > TimerFeedbackPtr;
typedef boost::shared_ptr< ::test_pkg::TimerFeedback const> TimerFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_pkg::TimerFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_pkg::TimerFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_pkg::TimerFeedback_<ContainerAllocator1> & lhs, const ::test_pkg::TimerFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.partial_time_elapsed == rhs.partial_time_elapsed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_pkg::TimerFeedback_<ContainerAllocator1> & lhs, const ::test_pkg::TimerFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test_pkg::TimerFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_pkg::TimerFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::TimerFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::TimerFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::TimerFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::TimerFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_pkg::TimerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc2a6c0f2999c8066afc8654096742d2";
  }

  static const char* value(const ::test_pkg::TimerFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc2a6c0f2999c806ULL;
  static const uint64_t static_value2 = 0x6afc8654096742d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_pkg::TimerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_pkg/TimerFeedback";
  }

  static const char* value(const ::test_pkg::TimerFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_pkg::TimerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float32 partial_time_elapsed # feedback \n"
"\n"
;
  }

  static const char* value(const ::test_pkg::TimerFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_pkg::TimerFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.partial_time_elapsed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimerFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_pkg::TimerFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_pkg::TimerFeedback_<ContainerAllocator>& v)
  {
    s << indent << "partial_time_elapsed: ";
    Printer<float>::stream(s, indent + "  ", v.partial_time_elapsed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_PKG_MESSAGE_TIMERFEEDBACK_H
