// Generated by gencpp from file test_pkg/TimerResult.msg
// DO NOT EDIT!


#ifndef TEST_PKG_MESSAGE_TIMERRESULT_H
#define TEST_PKG_MESSAGE_TIMERRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_pkg
{
template <class ContainerAllocator>
struct TimerResult_
{
  typedef TimerResult_<ContainerAllocator> Type;

  TimerResult_()
    : total_time_elapsed(0.0)  {
    }
  TimerResult_(const ContainerAllocator& _alloc)
    : total_time_elapsed(0.0)  {
  (void)_alloc;
    }



   typedef float _total_time_elapsed_type;
  _total_time_elapsed_type total_time_elapsed;





  typedef boost::shared_ptr< ::test_pkg::TimerResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_pkg::TimerResult_<ContainerAllocator> const> ConstPtr;

}; // struct TimerResult_

typedef ::test_pkg::TimerResult_<std::allocator<void> > TimerResult;

typedef boost::shared_ptr< ::test_pkg::TimerResult > TimerResultPtr;
typedef boost::shared_ptr< ::test_pkg::TimerResult const> TimerResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_pkg::TimerResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_pkg::TimerResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_pkg::TimerResult_<ContainerAllocator1> & lhs, const ::test_pkg::TimerResult_<ContainerAllocator2> & rhs)
{
  return lhs.total_time_elapsed == rhs.total_time_elapsed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_pkg::TimerResult_<ContainerAllocator1> & lhs, const ::test_pkg::TimerResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test_pkg::TimerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_pkg::TimerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::TimerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::TimerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::TimerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::TimerResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_pkg::TimerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a626cb8f0c7f276ce9ff106ac8fb36d3";
  }

  static const char* value(const ::test_pkg::TimerResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa626cb8f0c7f276cULL;
  static const uint64_t static_value2 = 0xe9ff106ac8fb36d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_pkg::TimerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_pkg/TimerResult";
  }

  static const char* value(const ::test_pkg::TimerResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_pkg::TimerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float32 total_time_elapsed # result\n"
;
  }

  static const char* value(const ::test_pkg::TimerResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_pkg::TimerResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_time_elapsed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimerResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_pkg::TimerResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_pkg::TimerResult_<ContainerAllocator>& v)
  {
    s << indent << "total_time_elapsed: ";
    Printer<float>::stream(s, indent + "  ", v.total_time_elapsed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_PKG_MESSAGE_TIMERRESULT_H
