// Generated by gencpp from file test_pkg/WordCount.msg
// DO NOT EDIT!


#ifndef TEST_PKG_MESSAGE_WORDCOUNT_H
#define TEST_PKG_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <test_pkg/WordCountRequest.h>
#include <test_pkg/WordCountResponse.h>


namespace test_pkg
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace test_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_pkg::WordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::test_pkg::WordCount&) { return value(); }
};

template<>
struct DataType< ::test_pkg::WordCount > {
  static const char* value()
  {
    return "test_pkg/WordCount";
  }

  static const char* value(const ::test_pkg::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::test_pkg::WordCountRequest> should match
// service_traits::MD5Sum< ::test_pkg::WordCount >
template<>
struct MD5Sum< ::test_pkg::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_pkg::WordCount >::value();
  }
  static const char* value(const ::test_pkg::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_pkg::WordCountRequest> should match
// service_traits::DataType< ::test_pkg::WordCount >
template<>
struct DataType< ::test_pkg::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::test_pkg::WordCount >::value();
  }
  static const char* value(const ::test_pkg::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_pkg::WordCountResponse> should match
// service_traits::MD5Sum< ::test_pkg::WordCount >
template<>
struct MD5Sum< ::test_pkg::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_pkg::WordCount >::value();
  }
  static const char* value(const ::test_pkg::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_pkg::WordCountResponse> should match
// service_traits::DataType< ::test_pkg::WordCount >
template<>
struct DataType< ::test_pkg::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::test_pkg::WordCount >::value();
  }
  static const char* value(const ::test_pkg::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_PKG_MESSAGE_WORDCOUNT_H
